<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="000D2023258" failures="1" tests="1" name="Default test" time="37.312" errors="0" timestamp="2024-02-08T11:11:58 CST">
  <testcase classname="encoderapp.Test.AllLoginTest" name="webLoginRestrictedAccess" time="5.929">
    <failure type="java.lang.AssertionError" message="expected [Oops! You are blocked from accessing this page. To gain access, contact your admin for support.] but found [Either your username or password is incorrect, please check and try again!]">
      <![CDATA[java.lang.AssertionError: expected [Oops! You are blocked from accessing this page. To gain access, contact your admin for support.] but found [Either your username or password is incorrect, please check and try again!]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at encoderapp.Test.AllLoginTest.webLoginRestrictedAccess(AllLoginTest.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- webLoginRestrictedAccess -->
  <testcase classname="encoderapp.Test.AllLoginTest" name="mobileLoginRestrictedAccess" time="0.0">
    <ignored/>
  </testcase> <!-- mobileLoginRestrictedAccess -->
  <testcase classname="encoderapp.Test.AllLoginTest" name="webLoginWithInvalidPassword" time="0.0">
    <ignored/>
  </testcase> <!-- webLoginWithInvalidPassword -->
  <testcase classname="encoderapp.Test.AllLoginTest" name="mobileLoginWithInvalidUserName" time="0.0">
    <ignored/>
  </testcase> <!-- mobileLoginWithInvalidUserName -->
  <testcase classname="encoderapp.Test.AllLoginTest" name="mobileLoginWithInvalidPassword" time="0.0">
    <ignored/>
  </testcase> <!-- mobileLoginWithInvalidPassword -->
  <testcase classname="encoderapp.Test.AllLoginTest" name="webLoginWithInvalidUserName" time="0.0">
    <ignored/>
  </testcase> <!-- webLoginWithInvalidUserName -->
</testsuite> <!-- Default test -->
